version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: calculos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      - DB_HOST=db  # Dirección del servicio PostgreSQL
      - DB_PORT=5432
      - DB_NAME=calculos
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
